version: '2'
services:
  node1:
    hostname: node1
    build: .
    command: /bin/bash -x /u01/oracle/sleep.sh &> sleep.log
    depends_on:
      - node2
      - node3
  node2:
    hostname: node2
    build: .
    command: /bin/bash -x /u01/oracle/sleep.sh &> sleep.log

  node3:
    hostname: node3
    build: .
    command: /bin/bash -x /u01/oracle/sleep.sh &> sleep.log

